spring:
    application:
        name: korkomat
    security:
        jwt:
            secret-key: 916rXznLgpdWRQBpaHbo8tvgkKN8fzwlpdSOvOu9uYc
            expiration: 900000 # 15 minutes
            refresh-token:
                expiration: 14d  # 14 days

    datasource:
        url: jdbc:postgresql://localhost:5433/korkomat_db
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop # Hibernate sam stworzy/zaktualizuje tabele na podstawie encji w Kotlinie
        show-sql: true # Wyświetla zapytania SQL w konsoli (przydatne do nauki!)
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect

app:
    admin:
        seed:
            enabled: ${ADMIN_SEED_ENABLED:true}
            email: ${ADMIN_EMAIL:admin@korkomat.pl}
            password: ${ADMIN_PASSWORD:admin123}
            first-name: ${ADMIN_FIRST_NAME:Admin}
            last-name: ${ADMIN_LAST_NAME:Korkomat}
